# Generated by Django 4.2.10 on 2024-07-04 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(6, message='このフィールドは6文字以上入力してください。'), django.core.validators.MaxLengthValidator(128, message='このフィールドは128文字以内で入力してください。')]),
        ),
    ]
